/** Call UI strings. Patient-facing text is PASHTO ONLY; staff UI is English. */
export const VIDEO_LABELS = {
  ps: {
    mute: 'غږ بند کړئ',
    unmute: 'غږ روښانه کړئ',
    cameraOff: 'کیمره بنده کړئ',
    cameraOn: 'کیمره روښانه کړئ',
    switchCamera: 'کیمره بدله کړئ',
    leave: 'مشوره پرېږدئ',
    reconnecting: 'اړیکه بیا جوړېږي…',
    connecting: 'وصل کېږي…',
    waitingForOther: 'ډاکټر ته انتظار وکړئ. ډاکټر به ډېر ژر راشي.',
    otherConnected: 'ډاکټر وصل دی',
    you: 'تاسو',
    cameraIsOff: 'کیمره بنده ده',
    // Low-bandwidth / audio-only
    audioOnly: 'یوازې غږ',
    backToVideo: 'ویډیو',
    audioOnlyActive: 'یوازې غږ فعال دی. دا لږ انټرنېټ مصرفوي.',
    audioOnlyNote: 'یوازې غږ د کمزوري انټرنېټ لپاره دی. ډاکټر ښايي بیا هم د معاینې لپاره ویډیو وغواړي.',
    audioOnlyPlaceholder: 'یوازې غږ — ویډیو بنده ده',
    videoPausedPlaceholder: 'ویډیو ودرول شوې ده — غږ روان دی',
    netGood: 'انټرنېټ ښه دی',
    netWeak: 'انټرنېټ کمزوری دی',
    netVeryWeak: 'انټرنېټ ډېر کمزوری دی',
    otherNetWeak: 'د ډاکټر انټرنېټ کمزوری دی',
    videoReduced: 'ستاسو انټرنېټ کمزوری دی. د ویډیو کیفیت کم شو.',
    videoPaused: 'ستاسو انټرنېټ ډېر کمزوری دی. ویډیو ودرول شوه چې ستاسو غږیزه مشوره دوام وکړي.',
    videoRestored: 'انټرنېټ ښه شو. ویډیو بېرته پیل شوه.',
    startedInAudio: 'ستاسو انټرنېټ کمزوری دی، نو مشوره په غږ پیل شوه. کله چې انټرنېټ ښه شي ویډیو به پیل شي، یا د کیمرې تڼۍ کېکاږئ.',
    connectionInterrupted: 'اړیکه پرې شوه. بیا وصل کېږي… مهرباني وکړئ دا پاڼه مه بندوئ.',
    reconnected: 'اړیکه بېرته جوړه شوه.',
    cameraUnavailable: 'کیمره کار نه کوي. مشوره په غږ دوام لري.',
    micUnavailable: 'مایکروفون کار نه کوي. د مایکروفون تڼۍ بیا کېکاږئ یا د براوزر اجازه وګورئ.',
    tapToHear: 'د اورېدلو لپاره دلته کېکاږئ',
    close: 'بند یې کړئ',
    // Pre-join
    joinAudioOnly: 'یوازې په غږ ورننوځئ',
    joinAudioOnlyHint: 'که انټرنېټ مو کمزوری وي، یوازې په غږ ورننوځئ. دا لږ انټرنېټ مصرفوي.',
    cameraDeniedAudio: 'کیمرې ته اجازه نشته یا کیمره ونه موندل شوه. تاسو کولی شئ مشوره یوازې په غږ وکړئ.',
    weakNetworkHint: 'ستاسو انټرنېټ کمزوری ښکاري. مشوره به لومړی په غږ پیل شي.',
    // After a dropped call
    droppedReassure: 'ستاسو مشوره نه ده پای ته رسېدلې. کله چې انټرنېټ بېرته راشي، «بیا هڅه وکړئ» کېکاږئ.',
    openedElsewhere: 'دا مشوره په بل ټیلیفون یا بله پاڼه کې پرانیستل شوه.',
  },
  en: {
    mute: 'Mute',
    unmute: 'Unmute',
    cameraOff: 'Camera off',
    cameraOn: 'Camera on',
    switchCamera: 'Switch camera',
    leave: 'Leave',
    reconnecting: 'Reconnecting…',
    connecting: 'Connecting…',
    waitingForOther: 'Waiting for the patient to join…',
    otherConnected: 'Patient connected',
    you: 'You',
    cameraIsOff: 'Camera is off',
    // Low-bandwidth / audio-only
    audioOnly: 'Audio only',
    backToVideo: 'Video',
    audioOnlyActive: 'Audio-only mode is on. This uses less internet data.',
    audioOnlyNote: 'Audio only is a fallback for weak internet, not a replacement for a video examination.',
    audioOnlyPlaceholder: 'Audio only — video is off',
    videoPausedPlaceholder: 'Video paused — audio continues',
    netGood: 'Good connection',
    netWeak: 'Weak connection',
    netVeryWeak: 'Very weak connection',
    otherNetWeak: 'Patient’s connection is weak',
    videoReduced: 'Your connection is weak. Video quality has been reduced.',
    videoPaused: 'Your connection is very weak. Video has been paused to keep the audio stable.',
    videoRestored: 'Connection improved. Video has resumed.',
    startedInAudio: 'Your connection is weak, so the call started with audio only. Video starts when it improves, or tap Camera.',
    connectionInterrupted: 'Connection interrupted. Reconnecting… keep this page open.',
    reconnected: 'Connection restored.',
    cameraUnavailable: 'The camera is not available. The consultation continues with audio.',
    micUnavailable: 'The microphone is not working. Tap the microphone button again or check the browser permission.',
    tapToHear: 'Tap here to turn on sound',
    close: 'Dismiss',
    // Pre-join
    joinAudioOnly: 'Join with audio only',
    joinAudioOnlyHint: 'On a weak connection, join with audio only. It uses less internet data.',
    cameraDeniedAudio: 'The camera is not available or not allowed. You can continue with audio only.',
    weakNetworkHint: 'Your connection looks weak. The call will start with audio first.',
    // After a dropped call
    droppedReassure: 'The consultation has not ended. Rejoin when the connection is back.',
    openedElsewhere: 'This consultation was opened on another device or tab.',
  },
} as const
export type VideoLang = keyof typeof VIDEO_LABELS
export type VideoLabels = (typeof VIDEO_LABELS)[VideoLang]
